easy_admin:
    entities:
#        # List the entity class name you want to manage
        - App\Entity\Genre
        - App\Entity\Editeur
        - App\Entity\Fournisseur
        - App\Entity\Product
#        - App\Entity\Category
        - App\Entity\User
